/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
    export interface GlobalComponents {
        AvatarAndUsername: typeof import('./src/components/mini/AvatarAndUsername.vue')['default']
        CalendarHeatmap: typeof import('./src/components/common/CalendarHeatmap.vue')['default']
        ElAffix: typeof import('element-plus/es')['ElAffix']
        ElAside: typeof import('element-plus/es')['ElAside']
        ElBadge: typeof import('element-plus/es')['ElBadge']
        ElButton: typeof import('element-plus/es')['ElButton']
        ElCol: typeof import('element-plus/es')['ElCol']
        ElContainer: typeof import('element-plus/es')['ElContainer']
        ElDivider: typeof import('element-plus/es')['ElDivider']
        ElDrawer: typeof import('element-plus/es')['ElDrawer']
        ElDropdown: typeof import('element-plus/es')['ElDropdown']
        ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
        ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
        ElFooter: typeof import('element-plus/es')['ElFooter']
        ElHeader: typeof import('element-plus/es')['ElHeader']
        ElIcon: typeof import('element-plus/es')['ElIcon']
        ElInput: typeof import('element-plus/es')['ElInput']
        ElLink: typeof import('element-plus/es')['ElLink']
        ElMain: typeof import('element-plus/es')['ElMain']
        ElMenu: typeof import('element-plus/es')['ElMenu']
        ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
        ElRow: typeof import('element-plus/es')['ElRow']
        ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
        ElTooltip: typeof import('element-plus/es')['ElTooltip']
        FooterBar: typeof import('./src/components/common/FooterBar.vue')['default']
        HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
        IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
        IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
        IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
        IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
        IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
        NavTop: typeof import('./src/components/common/navTop.vue')['default']
        RegisterAndLogin: typeof import('./src/components/mini/RegisterAndLogin.vue')['default']
        RouterLink: typeof import('vue-router')['RouterLink']
        RouterView: typeof import('vue-router')['RouterView']
        SearchBox: typeof import('./src/components/mini/SearchBox.vue')['default']
        TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
        TopNavBar: typeof import('./src/components/common/TopNavBar.vue')['default']
        WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
    }
}